### ISSUE TITLE
manage.py create_tenant --owner_id unrecognized argument

### ISSUE THREAD

**Issue by QuentinKp** [kiwitcms/tenants#60]
Hello,

I am trying to install Kiwi in multi tenant, but when I launch the command manage.py create_tenant the same way as the documentation, I get a first error : 

>  usage: manage.py create_tenant [-h] [--schema_name SCHEMA_NAME] [--name NAME]
>                                [--paid_until PAID_UNTIL] [--on_trial ON_TRIAL]
>                                [--owner OWNER] [--organization ORGANIZATION]
>                                [--domain-domain DOMAIN_DOMAIN]
>                                [--domain-tenant DOMAIN_TENANT]
>                                [--domain-is_primary DOMAIN_IS_PRIMARY] [-s]
>                                [--version] [-v {0,1,2,3}]
>                                [--settings SETTINGS] [--pythonpath PYTHONPATH]
>                                [--traceback] [--no-color] [--force-color]
>                                [--skip-checks]
> manage.py create_tenant: error: unrecognized arguments: --owner_id 1

I saw that the argument to use was --owner OWNER, what I did but I got another error :

> ValueError: Cannot assign "'admin'": "Tenant.owner" must be a "User" instance. 

I checked the database, and my superuser "admin" is there.

What info do you need from me about this ? I'm not sure if it is a bug or something I did wrong or maybe just the documentation needed to be updated ?

Thanks by advance

**Comment by atodorov** [comment]
This is dependent on https://github.com/tomturner/django-tenants/pull/337. 

Otherwise crate_tenant doesn't really work anyway. I'll ping the django-tenants maintainer but we need a new version from them before this can actually work.

**Comment by QuentinKp** [comment]
OK I will wait for this change to be done. 

Thank you for your quick answer.

**Comment by tomturner** [comment]
I have merged the change. I will try and do a release later today
